# Generated by Django 5.2.17 on 2026-09-07 07:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Turns on pgvector inside this database. Must run before any column
        # of type `vector` is created, so it is the first operation here.
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('preparation', 'Preparing for a procedure'), ('visiting', 'Visiting and wards'), ('department', 'Departments and locations'), ('administration', 'Admission, billing, and records'), ('access', 'Travel, parking, and accessibility')], default='department', max_length=32)),
                ('source_path', models.CharField(max_length=1024)),
                ('source_type', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF'), ('docx', 'Word document')], max_length=16)),
                ('checksum', models.CharField(max_length=64)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('heading_path', models.CharField(blank=True, max_length=512)),
                ('text', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'ordering': ['document_id', 'ordinal'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_gin')],
                'constraints': [models.UniqueConstraint(fields=('document', 'ordinal'), name='unique_chunk_ordinal')],
            },
        ),
    ]
