# Generated by Django 5.2.17 on 2026-09-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('zone', models.CharField(blank=True, help_text='e.g. Green Zone, level 2', max_length=60)),
                ('phone', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicians', to='appointments.department')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='appointments.clinician')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointments.slot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clinician',
            constraint=models.UniqueConstraint(fields=('full_name', 'department'), name='unique_clinician_per_department'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['starts_at', 'is_booked'], name='slot_availability_idx'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('clinician', 'starts_at'), name='unique_slot_per_clinician'),
        ),
    ]
