# Generated by Django 5.2.17 on 2026-09-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Patient'), ('assistant', 'Assistant')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, choices=[('information', 'Answered from documents'), ('appointment', 'Handled by the booking tools'), ('clinical', 'Refused — clinical advice'), ('emergency', 'Refused — urgent, redirected'), ('unsupported', 'Refused — outside the documents'), ('error', 'Something went wrong')], max_length=16)),
                ('search_query', models.TextField(blank=True, help_text='The standalone query actually searched')),
                ('refused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(help_text='The [1] the answer refers to')),
                ('document_title', models.CharField(max_length=255)),
                ('heading_path', models.CharField(blank=True, max_length=512)),
                ('excerpt', models.TextField(blank=True)),
                ('similarity', models.FloatField(default=0.0)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.chunk')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='assistant.message')),
            ],
            options={
                'ordering': ['message_id', 'ordinal'],
                'constraints': [models.UniqueConstraint(fields=('message', 'ordinal'), name='unique_citation_ordinal')],
            },
        ),
    ]
